---
title: "@KVB_Info Twitter stats"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  flexdashboard::flex_dashboard:
    vertical-layout: fill
    orientation: rows
    theme: yeti
---

```{r read-prep, message = FALSE}
options(stringsAsFactors = FALSE)
library(tidyverse)
library(highcharter)
library(DT)

fnames <- list.files(".", "kvb_tweets_.*\\.csv")

read_tweets <- function(path) {
  # id, created_at, text, (first_seen), (last_seen)
  downloaded <- as.POSIXct(strptime(path, "kvb_tweets_%Y%m%d_%H%M%S.csv", tz = "UTC"))
  data <- read_csv(path) %>%
    mutate(downloaded_at = downloaded)
  return(data)
}

tweets_all <- map_df(fnames, read_tweets) %>%
  group_by(id) %>%
  # TODO incorporate existing first_seen from consolidated data
  mutate(last_seen = max(downloaded_at)) %>%
  distinct(id, .keep_all = TRUE) %>%
  select(text, created_at, last_seen)

data_range_min <- min(tweets_all$first_seen)
data_range_max <- max(tweets_all$last_seen)

tweets_enriched <- tweets_all %>%
  mutate(text = tolower(text)) %>%
  mutate(
    cancelled = grepl("entfällt", text),
    lines = gsub("^(linie.*?) \\*.*", "\\1", text),
    lines = gsub("und", ",", lines),
    lines = gsub(" ", "", lines),
    lines = gsub("linien?", "", lines),
    lines = ifelse(grepl("^[0-9,]*$", lines), lines, "")
    #lines = strsplit(lines, ",")
    # ToDo extract lines first stop
  )

```


Ausfälle {data-orientation=rows}
================================================================================

Row
--------------------------------------------------------------------------------

### Ausfälle pro Linie (`r paste(data_range_min, "-", data_range_max)`)

```{r cancellation_overview}
tweets_cancelled <- tweets_enriched %>%
  filter(cancelled) %>%
  select(created_at, lines)

tmp_all <- tweets_cancelled %>%
  group_by(lines) %>%
  summarize(n = n()) %>%
  arrange(-n, as.numeric(lines))

# http://jkunst.com/highcharter/highcharts.html

highchart() %>% 
  hc_add_series(tmp_all, "column", hcaes(x = lines, y = n), name = "Ausfälle") %>%
  hc_plotOptions(
    series = list(
      showInLegend = FALSE,
      pointFormat = "{point.y}%"
    ),
    column = list(colorByPoint = TRUE)
  ) %>%
  hc_yAxis(title = list(text = "Ausfälle")) %>% 
  hc_xAxis(
    categories = tmp_all$lines,
    title = list(text = "Linie")
  )# %>%
  #hc_title(text = "Ausfälle jeder Linie") %>%
  #hc_subtitle(text = "(sämtliche verfügbaren Daten)") %>% 
  #hc_credits(
  #  enabled = TRUE, 
  #  text = "Erstellt aus @KVB_info tweets",
  #  href = "https://twitter.com/@KVB_Info",
  #  style = list(fontSize = "12px")
  #)

```

### Ausfälle pro Linie (7 Tage)

```{r cancellation_overview_week}
tmp_week <- tweets_cancelled %>%
  filter(created_at >= (Sys.time() - as.difftime(7, units = "days"))) %>%
  group_by(lines) %>%
  summarize(n = n()) %>%
  arrange(-n, as.numeric(lines))

highchart() %>% 
  hc_add_series(tmp_week, "column", hcaes(x = lines, y = n), name = "Ausfall") %>%
  hc_plotOptions(
    series = list(
      showInLegend = FALSE,
      pointFormat = "{point.y}%"
    ),
    column = list(colorByPoint = TRUE)
  ) %>%
  hc_yAxis(title = list(text = "Ausfälle")) %>% 
  hc_xAxis(
    categories = tmp_all$lines,
    title = list(text = "Linie")
  )

```

### Ausfälle pro Linie (24 Stunden)

```{r cancellation_overview_day}
tmp_24h <- tweets_cancelled %>%
  filter(created_at >= (Sys.time() - as.difftime(1, units = "days"))) %>%
  group_by(lines) %>%
  summarize(n = n()) %>%
  arrange(-n, as.numeric(lines))

highchart() %>% 
  hc_add_series(tmp_24h, "column", hcaes(x = lines, y = n), name = "Ausfall") %>%
  hc_plotOptions(
    series = list(
      showInLegend = FALSE,
      pointFormat = "{point.y}%"
    ),
    column = list(colorByPoint = TRUE)
  ) %>%
  hc_yAxis(title = list(text = "Ausfälle")) %>% 
  hc_xAxis(
    categories = tmp_all$lines,
    title = list(text = "Linie")
  )

```

Row
--------------------------------------------------------------------------------

### Ausfälle pro Wochentag und Stunde (`r paste(data_range_min, "-", data_range_max)`)

```{r cancellation_heatmap}
days <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")
hours <- seq.POSIXt(as.POSIXct(Sys.Date()), 
                    as.POSIXct(Sys.Date()+1), 
                    by = "hour") %>% 
  format("%H") %>% 
  unique() %>%
  sort()

tmp_heat <- tweets_enriched %>%
  mutate(hour = strftime(created_at, "%H")) %>%
  mutate(wday = weekdays(created_at)) %>%
  group_by(hour, wday) %>%
  summarise(n = n()) %>%
  ungroup %>%
  mutate(wday = factor(wday, levels = days))

# impute missing data 
# all possible combinations of weekdays and hours
# ToDo this could be neater
lookup <- expand.grid(hour = hours, 
                      wday = days, 
                      stringsAsFactors = FALSE, KEEP.OUT.ATTRS = FALSE) %>% 
  mutate(wday = factor(wday, levels = days))
missing <- lookup %>% 
  anti_join(tmp_heat, by = c("hour", "wday")) %>% 
  mutate(n = 0)
heatmap_complete <- tmp_heat %>%
  rbind(missing) %>%
  arrange(wday, hour)

fntltp <- JS("function(){return 'Ausfälle : ' + this.point.n;}")
  
# define discrete steps for colouring heatmap instead of gradient for a better 
# visibility
#by_steps <- 5
#max_step <- by_steps*ceiling(max(heatmap_complete$n)/by_steps)
#steps <- seq(0, max_step, by = 5)
#nr_steps <- length(steps)
#min_color <- "#FFFFFF"
#max_color <- "#018786"
#steps_colors <- colorRampPalette(c(min_color, max_color))(nr_steps)[2:nr_steps]
#data_classes <- tibble(to = steps, color = c("#343E48", steps_colors)) %>% 
#  mutate(from = to - (by_steps - 1)) %>% 
#  mutate(from = ifelse(to == 0, 0, from)) %>% 
#  list_parse()
  
hchart(heatmap_complete, "heatmap", hcaes(x = hour, y = wday, value = n)) %>%
  hc_colorAxis(type = "linear") %>%
  hc_tooltip(formatter = fntltp) %>%
  #hc_title(text = "Ausfälle pro Wochentag und Stunde") %>%
  hc_xAxis(title = list(
    text = "Stunde"),
    gridLineWidth = 1
  ) %>%
  hc_yAxis(
    title = list(text = "Wochentag"),
    type = "datetime",
    reversed = TRUE
  ) %>%
  #hc_colorAxis(dataClasses = data_classes) %>%
  hc_plotOptions(marginTop = 40,
                 marginBottom = 80,
                 plotBorderWidth = 1) %>% 
  hc_legend(labelFormatter = JS("function () {
if (this.from == 0) {
  return this.from;
} else { 
  return (this.from || '<') + ' - ' + (this.to || '>');
}
  }"),
  valueDecimals = 0,
  symbolRadius = 0, 
  padding = 12)

```

### Ausfälle pro Stunde (`r paste(data_range_min, "-", data_range_max)`)

```{r heatmap_supplement_hours}
heatmap_hours <- heatmap_complete %>%
  group_by(hour) %>%
  summarize(n = sum(n))

highchart() %>%
  hc_add_series(heatmap_hours, "column", hcaes(x = hour, y = n)) %>%
  hc_xAxis(
    categories = hours,
    title = list(text = "Stunde")
  )

```

### Ausfälle pro Wochentag (`r paste(data_range_min, "-", data_range_max)`)

```{r heatmap_supplement_wdays}
heatmap_wdays <- heatmap_complete %>%
  group_by(wday) %>%
  summarize(n = sum(n))

highchart() %>%
  hc_add_series(heatmap_wdays, "column", hcaes(x = wday, y = n)) %>%
  hc_xAxis(
    categories = days,
    title = list(text = "Wochentag")
  )

```


Löschverhalten
================================================================================

Row
--------------------------------------------------------------------------------

### Anzeigedauer der Tweets (Stunden)

```{r tweets_lifetime}
tweets_deletion <- tweets_all %>%
  ungroup() %>%
  mutate(ttl = as.numeric(last_seen - created_at, units = "hours"),
         deleted = (last_seen != max(last_seen))
  ) %>%
  filter(deleted)

hist(tweets_deletion$ttl)
```

### Häufigkeit der Löschung

```{r deletion_frequency}
deletion_events <- tweets_deletion %>%
  group_by(last_seen) %>%
  summarize(
    num_deleted = n(),
    created_min = min(created_at),
    created_max = max(created_at)
  ) %>%
  mutate(
    last_seen = paste(last_seen),
    created_min = paste(created_min),
    created_max = paste(created_max)
  )

datatable(deletion_events)
```
